version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm start
    working_dir: /app
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

# không sử dụng được